### ISSUE TITLE
Errors in the installation of the developers scripts

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/Hermes#6]
Running 
` ./install.sh -d ~/Projects/2020/Hermes`

Results in:

mkdir: cannot create directory ‘’: No such file or directory
fatal: destination path 'pyHermes' already exists and is not an empty directory.
Git tree pyHermes exist, trying to pull
Already up to date.
fatal: destination path 'JsonExample' already exists and is not an empty directory.
Git tree JsonExample exist, trying to pull
Already up to date.
"sha256:518df783c4d6387c0419b1abf7c0544f7c49cddb443d6c7b015eb1ee7aec5738"
Docker image doesn't exist, will try to download
Error response from daemon: manifest for registry.gitlab.com/daviddaish/freecad_docker_env:ee7e3ecee4ca not found
Docker image pull failed
Docker launch script generation for users
Docker launch script generation for developers
"/home/yehuda/Development/pyHermes//source" appears to be a git tree, will try to checkout
Hash  0.18-1194-g5a352ea63 already cheked out
./install.sh: line 123: /home/yehuda/Development/pyHermes/freecad_5a352ea63_git.diff: No such file or directory
dot_local/
dot_local/bin/
.
.
.
.
dot_local/bin/__pycache__/rst2latex.cpython-37.pyc
Expanding FreeCad .bashrc for building
Build command that runs qmake and make: /mnt/source/build_script.sh
++ nproc
+ cmake -j8 -D BOOST_ROOT=/usr/local/include/boost -D BUILD_QT5=ON -D BUILD_FEM=ON -D BUILD_SANDBOX=ON -D PYTHON_LIBRARY=/usr/local/lib/libpython3.7m.so -D PYTHON_INCLUDE_DIR=/usr/local/include/python3.7 -D PYTHON_PACKAGES_PATH=/usr/local/lib/python3.7/site-packages -D PYTHON_EXECUTABLE=/usr/local/bin/python3 -D SHIBOKEN_INCLUDE_DIR=/usr/local/lib/python3.7/site-packages/shiboken2_generator/include -D SHIBOKEN_LIBRARY=/usr/local/lib/python3.7/site-packages/shiboken2/libshiboken2.cpython-37m-x86_64-linux-gnu.so.5 -D PYSIDE_INCLUDE_DIR=/usr/local/lib/python3.7/site-packages/PySide2/include -D PYSIDE_LIBRARY=/usr/local/lib/python3.7/site-packages/PySide2/libpyside2.cpython-37m-x86_64-linux-gnu.so.5 -D PYSIDE2RCCBINARY=/usr/local/lib/python3.7/site-packages/PySide2/pyside2-rcc -D 'FREECAD_USE_QTWEBMODULE=Qt\ Webkit' -S /mnt/source -B /mnt/build
-- Compiler: GNU, version: 6.3.0
-- prefix: /usr/local
-- datadir: data
-- docdir: doc
-- includedir: include
-- libdir: /usr/local/lib
-- cmake: 3.13.4
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   filesystem
--   program_options
--   regex
--   system
--   thread
--   chrono
--   date_time
--   atomic
-- Found Xerces-C: /usr/local/lib/libxerces-c.so
-- PyCXX found:
--   Headers:  /mnt/source/src
--   Sources:  /mnt/source/src/CXX
--   Version:  6.2.8
-- -- Found OCE/OpenCASCADE version: 7.3.0
-- -- OCE/OpenCASCADE include directory: /usr/local/include/opencascade
-- -- OCE/OpenCASCADE shared libraries directory: /usr/local/lib
CMake Error at CMakeLists.txt:727 (find_package):
  Could not find a package configuration file provided by "VTK" with any of
  the following names:

    VTKConfig.cmake
    vtk-config.cmake

  Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
  to a directory containing one of the above files.  If "VTK" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/mnt/build/CMakeFiles/CMakeOutput.log".
See also "/mnt/build/CMakeFiles/CMakeError.log".
+ cd /mnt/build

**Comment by jackitg** [comment]
Fixed in commit ab63d96

**Comment by yehudarav** [comment]
Hi, 

Still getting the VTK errors after 
`./install.sh -d ~/Projects/2020`

-- Found Xerces-C: /usr/local/lib/libxerces-c.so
-- PyCXX found:
--   Headers:  /mnt/source/src
--   Sources:  /mnt/source/src/CXX
--   Version:  6.2.8
-- -- Found OCE/OpenCASCADE version: 7.3.0
-- -- OCE/OpenCASCADE include directory: /usr/local/include/opencascade
-- -- OCE/OpenCASCADE shared libraries directory: /usr/local/lib
CMake Error at CMakeLists.txt:727 (find_package):
  Could not find a package configuration file provided by "VTK" with any of
  the following names:

    VTKConfig.cmake
    vtk-config.cmake

  Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
  to a directory containing one of the above files.  If "VTK" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/mnt/build/CMakeFiles/CMakeOutput.log".
See also "/mnt/build/CMakeFiles/CMakeError.log".
+ cd /mnt/build
++ nproc
+ make -j 8
make: *** No targets specified and no makefile found.  Stop.
If fixing error that do not require qmake, run the following make command:
make -j $(nproc)
